### PR TITLE
feat: plivo sms support

### PR DESCRIPTION
**Pull request by kapilpaul**
add support for SMS provider `plivo`

### CODE REVIEW

**Comment by tareq1988** [comment]
Please add the auth_id and token validation on the `validate` method. Maybe call to [this endpoint](https://www.plivo.com/docs/sms/api/message#list-all-messages) to get a valid JSON response.

```
https://api.plivo.com/v1/Account/{auth_id}/Message/
```

**Comment by kapilpaul** [comment]
Okay I will try to validate by sending a sms.

**Comment by tareq1988** [comment]
Don't try to send an SMS, try to check if you can access the API correctly with the API credentials provided. We are not storing any invalid API keys.

Like [this here](https://github.com/weDevsOfficial/texty/blob/master/includes/Gateways/Twilio.php#L128).

**Comment by kapilpaul** [comment]
added validation for plivo

**Comment by tareq1988** [comment]
@kapilpaul Thanks for the contribution :)

**Pull request merged**
